# Generated by Django 3.0.7 on 2020-07-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='akskate.Localidad')),
            ],
        ),
    ]
