# Generated by Django 3.0.7 on 2020-07-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0003_order_orderitems_product_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
