# Generated by Django 3.0.7 on 2020-07-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0010_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
