# Generated by Django 3.0.7 on 2020-07-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0011_remove_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Initiated', max_length=64),
        ),
    ]
