# Generated by Django 3.0.7 on 2020-07-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0013_auto_20200710_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wheels',
            name='price',
            field=models.IntegerField(),
        ),
    ]
