# Generated by Django 3.0.7 on 2020-07-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0018_decks_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='category',
        ),
    ]
