# Generated by Django 3.0.7 on 2020-07-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0019_remove_decks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
