# Generated by Django 3.0.7 on 2020-07-16 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0021_remove_decks_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('spots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akskate.Spots')),
            ],
        ),
    ]
