# Generated by Django 3.0.7 on 2020-07-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0022_imagesspots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesspots',
            old_name='spots',
            new_name='spot',
        ),
    ]
