# Generated by Django 3.0.7 on 2020-07-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0023_auto_20200715_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lijas',
        ),
    ]
