# Generated by Django 3.0.7 on 2020-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0027_auto_20200721_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=0),
        ),
    ]
