# Generated by Django 3.0.7 on 2020-07-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0028_auto_20200721_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
