# Generated by Django 3.0.7 on 2020-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0029_auto_20200721_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='direction',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
