# Generated by Django 3.0.7 on 2020-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akskate', '0031_spots_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='chat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
